apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: authorization-service
  name: authorization-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: authorization-service
  template:
    metadata:
      annotations:
      labels:
        app: authorization-service
    spec:  
      shareProcessNamespace: true
      containers:
      - envFrom:
        - configMapRef:
            name: opentp
        image: quay.io/phagen/authorization-service:1.1.0
        imagePullPolicy: Always
        name: authorization-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - name: splunk-go-instrumentation
        image: quay.io/phagen/otel-go-instrumentation:1.0
        imagePullPolicy: IfNotPresent
        env:
          - name: NODE_IP
            valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          - name: OTEL_GO_AUTO_TARGET_EXE
            value: "/app/service"
          - name: OTEL_TRACES_EXPORTER
            value: "otlp"
          - name:  OTEL_EXPORTER_OTLP_PROTOCOL
            value: "grpc"  
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://$(NODE_IP):4317"
          - name: OTEL_SERVICE_NAME
            value: "authorization-service"
          - name: OTEL_PROPAGATORS
            value: "tracecontext,baggage"
          - name: OTEL_GO_AUTO_GLOBAL
            value: "true"     
          - name: OTEL_LOG_LEVEL
            value: "Debug"         
        securityContext:
          runAsUser: 0
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: authorization-service
  namespace: default
spec:
  ports:
  - name: auth
    port: 4000
    protocol: TCP
    targetPort: 4000
  - name: login
    port: 50551
    protocol: TCP
    targetPort: 50551
  selector:
    app: authorization-service
  sessionAffinity: ClientIP
  type: ClusterIP
        


  
