apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: authorization-service
    app.kubernetes.io/managed-by: Helm
  name: authorization-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: authorization-service
  template:
    metadata:
      annotations:
        # instrumentation.opentelemetry.io/inject-go: default/splunk-otel-collector
        # instrumentation.opentelemetry.io/otel-go-auto-target-exe: /app/service
      labels:
        app: authorization-service
    spec:  
      shareProcessNamespace: true
      containers:
      - envFrom:
        - configMapRef:
            name: opentp
        image: ettec/otp-authorization-service:1.1.0
        imagePullPolicy: Always
        name: authorization-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - name: splunk-go-instrumentation
        image: quay.io/phagen/otel-go-instrumentation:1.0
        imagePullPolicy: IfNotPresent
        env:
          - name: NODE_IP
            valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          - name: OTEL_GO_AUTO_TARGET_EXE
            value: "/app/service"
          - name: OTEL_TRACES_EXPORTER
            value: "otlp"
          - name:  OTEL_EXPORTER_OTLP_PROTOCOL
            value: "grpc"  
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://$(NODE_IP):4317"
          - name: OTEL_SERVICE_NAME
            value: "authorization-service"
          - name: OTEL_PROPAGATORS
            value: "tracecontext,baggage"
          - name: OTEL_GO_AUTO_GLOBAL
            value: "true"     
          - name: OTEL_LOG_LEVEL
            value: "Debug"         
        securityContext:
          runAsUser: 0
          privileged: true


  
