apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      meta.helm.sh/release-name: otp-1.1.0
      meta.helm.sh/release-namespace: default
    creationTimestamp: "2024-07-22T13:27:33Z"
    generation: 1
    labels:
      app: client-config-service
      app.kubernetes.io/managed-by: Helm
    name: client-config-service
    namespace: default
    resourceVersion: "2725"
    uid: 5e2570e3-f43a-4025-9efa-13563ae9a16f
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: client-config-service
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: client-config-service
      spec:
        containers:
        - envFrom:
          - configMapRef:
              name: opentp
          image: ettec/otp-client-config-service:1.1.0
          imagePullPolicy: Always
          name: client-config-service
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - name: splunk-go-instrumentation
          image: quay.io/phagen/otel-go-instrumentation:1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_IP
              valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
            - name: OTEL_GO_AUTO_TARGET_EXE
              value: /app/service
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://$(NODE_IP):4317"
            - name: OTEL_SERVICE_NAME
              value: "client-config-service"
            - name: OTEL_PROPAGATORS
              value: "tracecontext,baggage"          
        securityContext:
          runAsUser: 0
          privileged: true

        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 2
    conditions:
    - lastTransitionTime: "2024-07-22T13:28:00Z"
      lastUpdateTime: "2024-07-22T13:28:00Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2024-07-22T13:27:33Z"
      lastUpdateTime: "2024-07-22T13:28:00Z"
      message: ReplicaSet "client-config-service-6f67b676c8" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: otp-1.1.0
      meta.helm.sh/release-namespace: default
    creationTimestamp: "2024-07-22T13:27:33Z"
    labels:
      app: client-config-service
      app.kubernetes.io/managed-by: Helm
    name: client-config-service
    namespace: default
    resourceVersion: "2230"
    uid: dad8917d-9680-4aeb-bdfd-526e29677258
  spec:
    clusterIP: 10.43.223.166
    clusterIPs:
    - 10.43.223.166
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 50551
      protocol: TCP
      targetPort: 50551
    selector:
      app: client-config-service
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
