apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: iexg-order-gateway
  name: iexg-order-gateway
  namespace: default
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: iexg-order-gateway
  serviceName: iexg-order-gateway
  template:
    metadata:
      labels:
        app: iexg-order-gateway
        mic: IEXG
        servicetype: execution-venue
    spec:
      shareProcessNamespace: true
      serviceAccount: otpservice
      serviceAccountName: otpservice
      terminationGracePeriodSeconds: 30
      containers:
      - env:
        - name: FIX_SOCKET_CONNECT_HOST
          value: iexgsimulator
        - name: FIX_SOCKET_CONNECT_PORT
          value: "9876"
        - name: FIX_LOG_FILE_PATH
          value: /open-trading-platform/iexg-order-gateway
        - name: FIX_FILE_STORE_PATH
          value: /open-trading-platform/iexg-order-gateway
        - name: MIC
          value: IEXG
        - name: ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        envFrom:
        - configMapRef:
            name: opentp
        image: quay.io/phagen/fix-sim-execution-venue:1.1.0
        imagePullPolicy: Always
        name: iexg-order-gateway
        ports:
        - containerPort: 50551
          name: api
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /open-trading-platform
          name: execution-venue-storage
        volumes:
        - emptyDir: {}
        name: execution-venue-storage  
      - name: splunk-go-instrumentation
        image: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:v0.14.0-alpha
        imagePullPolicy: IfNotPresent
        env:
          - name: NODE_IP
            valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          - name: OTEL_GO_AUTO_TARGET_EXE
            value: "/app/service"
          - name: OTEL_TRACES_EXPORTER
            value: "otlp"
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: "grpc"
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://$(NODE_IP):4317"
          - name: OTEL_SERVICE_NAME
            value: "iexg-market-data-gateway"
          - name: OTEL_PROPAGATORS
            value: "tracecontext,baggage"
          - name: OTEL_GO_AUTO_GLOBAL
            value: "true"
          - name: OTEL_LOG_LEVEL
            value: "Debug"
        securityContext:
          runAsUser: 0
          privileged: true
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"          

  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  updatedReplicas: 2
