apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: iexg-market-data-gateway
  name: iexg-market-data-gateway
  namespace: default
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: iexg-market-data-gateway
  serviceName: iexg-market-data-gateway
  template:
    metadata:
      labels:
        app: iexg-market-data-gateway
        mic: IEXG
        servicetype: market-data-gateway
    spec:
      shareProcessNamespace: true
      serviceAccount: otpservice
      serviceAccountName: otpservice
      terminationGracePeriodSeconds: 30
      containers:
      - env:
        - name: FIX_SIM_ADDRESS
          value: iexgsimulator:50051
        - name: GATEWAY_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: quay.io/phagen/market-data-gateway-fixsim:1.1.0
        imagePullPolicy: Always
        name: iexg-market-data-gateway
        ports:
        - containerPort: 50551
          name: api
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File 
      - name: splunk-go-instrumentation
        image: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:v0.14.0-alpha
        imagePullPolicy: IfNotPresent
        env:
          - name: NODE_IP
            valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          - name: OTEL_GO_AUTO_TARGET_EXE
            value: "/app/service"
          - name: OTEL_TRACES_EXPORTER
            value: "otlp"
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: "grpc"
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://$(NODE_IP):4317"
          - name: OTEL_SERVICE_NAME
            value: "iexg-market-data-gateway"
          - name: OTEL_PROPAGATORS
            value: "tracecontext,baggage"
          - name: OTEL_GO_AUTO_GLOBAL
            value: "true"
          - name: OTEL_LOG_LEVEL
            value: "Debug"
        securityContext:
          runAsUser: 0
          privileged: true
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate

