apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      meta.helm.sh/release-name: otp-1.1.0
      meta.helm.sh/release-namespace: default
    creationTimestamp: "2024-07-22T13:27:33Z"
    generation: 1
    labels:
      app: market-data-service
      app.kubernetes.io/managed-by: Helm
    name: market-data-service
    namespace: default
    resourceVersion: "4021"
    uid: 1fa72e32-cfb8-466a-9a6f-f2574bc7f200
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: market-data-service
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          prometheus.io/port: "8080"
          prometheus.io/scrape: "true"
        creationTimestamp: null
        labels:
          app: market-data-service
      spec:
        containers:
        - env:
          - name: MDS_ID
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          image: ettec/otp-market-data-service:1.1.0
          imagePullPolicy: Always
          name: market-data-service
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - name: splunk-go-instrumentation
          image: quay.io/phagen/otel-go-instrumentation:1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_IP
              valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
            - name: OTEL_GO_AUTO_TARGET_EXE
              value: /app/service
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://$(NODE_IP):4317"
            - name: OTEL_SERVICE_NAME
              value: "market-data-service"
            - name: OTEL_PROPAGATORS
              value: "tracecontext,baggage"          
          securityContext:
            runAsUser: 0
            privileged: true  
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: otpservice
        serviceAccountName: otpservice
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 2
    conditions:
    - lastTransitionTime: "2024-07-22T13:27:33Z"
      lastUpdateTime: "2024-07-22T13:27:52Z"
      message: ReplicaSet "market-data-service-55c9b9bd67" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2024-07-22T13:39:29Z"
      lastUpdateTime: "2024-07-22T13:39:29Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: otp-1.1.0
      meta.helm.sh/release-namespace: default
    creationTimestamp: "2024-07-22T13:27:33Z"
    labels:
      app: market-data-service
      app.kubernetes.io/managed-by: Helm
    name: market-data-service
    namespace: default
    resourceVersion: "2206"
    uid: 3fcb95cc-6fd8-446a-bc0f-fed9d35990a0
  spec:
    clusterIP: 10.43.166.4
    clusterIPs:
    - 10.43.166.4
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: api
      port: 50551
      protocol: TCP
      targetPort: 50551
    selector:
      app: market-data-service
    sessionAffinity: ClientIP
    sessionAffinityConfig:
      clientIP:
        timeoutSeconds: 10800
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
