apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-data-service
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: market-data-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: market-data-service
    spec:
      shareProcessNamespace: true   
      containers:
      - env:
        - name: MDS_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: quay.io/phagen/market-data-service:1.1.0
        imagePullPolicy: Always
        name: market-data-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - name: splunk-go-instrumentation
        image: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:v0.14.0-alpha
        imagePullPolicy: IfNotPresent
        env:
          - name: NODE_IP
            valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          - name: OTEL_GO_AUTO_TARGET_EXE
            value: "/app/service"
          - name: OTEL_TRACES_EXPORTER
            value: "otlp"
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: "grpc"
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://$(NODE_IP):4317"
          - name: OTEL_SERVICE_NAME
            value: "market-data-service"
          - name: OTEL_PROPAGATORS
            value: "tracecontext,baggage"
          - name: OTEL_GO_AUTO_GLOBAL
            value: "true"
          - name: OTEL_LOG_LEVEL
            value: "Debug"
        securityContext:
          runAsUser: 0
          privileged: true
      serviceAccount: otpservice
      serviceAccountName: otpservice
---
apiVersion: v1
kind: Service
metadata:
  name: market-data-service
  namespace: default
spec:
  ports:
  - name: api
    port: 50551
    protocol: TCP
    targetPort: 50551
  - name: prometheus
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: market-data-service
  sessionAffinity: ClientIP
  type: ClusterIP