apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      meta.helm.sh/release-name: otp-1.1.0
      meta.helm.sh/release-namespace: default
    creationTimestamp: "2024-07-22T13:27:33Z"
    generation: 1
    labels:
      app: order-monitor
      app.kubernetes.io/managed-by: Helm
    name: order-monitor
    namespace: default
    resourceVersion: "2792"
    uid: c814838a-6d72-441a-b806-15d256cb3c73
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: order-monitor
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          prometheus.io/port: "8080"
          prometheus.io/scrape: "true"
        creationTimestamp: null
        labels:
          app: order-monitor
      spec:
        containers:
        - envFrom:
          - configMapRef:
              name: opentp
          image: ettec/otp-order-monitor:1.1.0
          imagePullPolicy: Always
          name: order-monitor
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - name: splunk-go-instrumentation
          image: quay.io/phagen/otel-go-instrumentation:1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_IP
              valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
            - name: OTEL_GO_AUTO_TARGET_EXE
              value: /app/service
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://$(NODE_IP):4317"
            - name: OTEL_SERVICE_NAME
              value: "order-monitor"
            - name: OTEL_PROPAGATORS
              value: "tracecontext,baggage"          
          securityContext:
            runAsUser: 0
            privileged: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: otpservice
        serviceAccountName: otpservice
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2024-07-22T13:28:05Z"
      lastUpdateTime: "2024-07-22T13:28:05Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2024-07-22T13:27:33Z"
      lastUpdateTime: "2024-07-22T13:28:05Z"
      message: ReplicaSet "order-monitor-598b579f87" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: otp-1.1.0
      meta.helm.sh/release-namespace: default
    creationTimestamp: "2024-07-22T13:27:33Z"
    labels:
      app: order-monitor
      app.kubernetes.io/managed-by: Helm
    name: order-monitor
    namespace: default
    resourceVersion: "2239"
    uid: 56163b11-7b6d-4353-adf7-b0411104d09f
  spec:
    clusterIP: 10.43.8.101
    clusterIPs:
    - 10.43.8.101
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 50551
      protocol: TCP
      targetPort: 50551
    selector:
      app: order-monitor
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
