apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order-monitor
  name: order-monitor
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: order-monitor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: order-monitor
    spec:
      shareProcessNamespace: true
      serviceAccountName: otpservice
      terminationGracePeriodSeconds: 30
      containers:
      - envFrom:
        - configMapRef:
            name: opentp
        image: quay.io/phagen/order-monitor:1.1.0
        imagePullPolicy: Always
        name: order-monitor
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - name: splunk-go-instrumentation
        image: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:v0.14.0-alpha
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_IP
          valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        - name: OTEL_GO_AUTO_TARGET_EXE
          value: "/app/service"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://$(NODE_IP):4317"
        - name: OTEL_SERVICE_NAME
          value: "order-monitor"
        - name: OTEL_PROPAGATORS
          value: "tracecontext,baggage"
        - name: OTEL_GO_AUTO_GLOBAL
          value: "true"
        - name: OTEL_LOG_LEVEL
          value: "Debug"
        securityContext:
          runAsUser: 0
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-monitor
  name: order-monitor
  namespace: default
spec:
  ports:
  - port: 50551
    name: internal
    protocol: TCP
    targetPort: 50551
  - port: 8080
    name: prometheus
    protocol: TCP
    targetPort: 8080
  selector:
    app: order-monitor
  sessionAffinity: None
  type: ClusterIP