apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      meta.helm.sh/release-name: otp-1.1.0
      meta.helm.sh/release-namespace: default
    creationTimestamp: "2024-07-22T13:27:33Z"
    generation: 1
    labels:
      app: order-router
      app.kubernetes.io/managed-by: Helm
    name: order-router
    namespace: default
    resourceVersion: "2667"
    uid: 0d9ed7bc-23a5-48c8-9239-7430a29b1482
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: order-router
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: order-router
      spec:
        containers:
        - image: ettec/otp-order-router:1.1.0
          imagePullPolicy: Always
          name: order-router
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - name: splunk-go-instrumentation
          image: quay.io/phagen/otel-go-instrumentation:1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_IP
              valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
            - name: OTEL_GO_AUTO_TARGET_EXE
              value: /app/service
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://$(NODE_IP):4317"
            - name: OTEL_SERVICE_NAME
              value: "order-router"
            - name: OTEL_PROPAGATORS
              value: "tracecontext,baggage"          
          securityContext:
            runAsUser: 0
            privileged: true  
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: otpservice
        serviceAccountName: otpservice
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 2
    conditions:
    - lastTransitionTime: "2024-07-22T13:27:56Z"
      lastUpdateTime: "2024-07-22T13:27:56Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2024-07-22T13:27:33Z"
      lastUpdateTime: "2024-07-22T13:27:56Z"
      message: ReplicaSet "order-router-59fb7d9fbc" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: otp-1.1.0
      meta.helm.sh/release-namespace: default
    creationTimestamp: "2024-07-22T13:27:33Z"
    labels:
      app: order-router
      app.kubernetes.io/managed-by: Helm
    name: order-router
    namespace: default
    resourceVersion: "2219"
    uid: 832951d9-a754-415e-8770-8a3f14856e56
  spec:
    clusterIP: 10.43.103.170
    clusterIPs:
    - 10.43.103.170
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: api
      port: 50581
      protocol: TCP
      targetPort: 50581
    selector:
      app: order-router
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
