---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: static-data-service
  name: static-data-service
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: static-data-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: static-data-service
    spec:
      shareProcessNamespace: true
      serviceAccountName: otpservice
      terminationGracePeriodSeconds: 30
      containers:
      - envFrom:
        - configMapRef:
            name: opentp
        image: quay.io/phagen/static-data-service:1.1.0
        imagePullPolicy: Always
        name: static-data-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - name: splunk-go-instrumentation
        image: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:v0.14.0-alpha
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_IP
          valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        - name: OTEL_GO_AUTO_TARGET_EXE
          value: "/app/service"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://$(NODE_IP):4317"
        - name: OTEL_SERVICE_NAME
          value: "static-data-service"
        - name: OTEL_PROPAGATORS
          value: "tracecontext,baggage"
        - name: OTEL_GO_AUTO_GLOBAL
          value: "true"
        - name: OTEL_LOG_LEVEL
          value: "Debug"
        securityContext:
          runAsUser: 0
          privileged: true 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: static-data-service
  name: static-data-service
  namespace: default
spec:
  ports:
  - name: api
    port: 50551
    protocol: TCP
    targetPort: 50551
  selector:
    app: static-data-service
  sessionAffinity: None
  type: ClusterIP

