apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    meta.helm.sh/release-name: otp-1.1.0
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-07-17T08:20:37Z"
  generation: 9
  labels:
    app: authorization-service
    app.kubernetes.io/managed-by: Helm
  name: authorization-service
  namespace: default
  resourceVersion: "348143"
  uid: 1c519131-8520-4254-a9d6-e2e02a5d2a91
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: authorization-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-go: default/splunk-otel-collector
        instrumentation.opentelemetry.io/otel-go-auto-target-exe: /app/service
        kubectl.kubernetes.io/restartedAt: "2024-07-20T05:24:58Z"
      creationTimestamp: null
      labels:
        app: authorization-service
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: opentp
        image: ettec/otp-authorization-service:1.1.0
        imagePullPolicy: Always
        name: authorization-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - name: splunk-go-instrumentation
        image: quay.io/phagen/otel-go-instrumentation:1.0
        env:
          - name: NODE_IP
            valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          - name: OTEL_GO_AUTO_TARGET_EXE
            value: /app/service
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://$(NODE_IP):4317"
          - name: OTEL_SERVICE_NAME
            value: "authorization-service"
        securityContext:
          runAsUser: 0
          capabilities:
             add:
                - SYS_PTRACE
          privileged: true
        volumeMounts:
          - mountPath: /sys/kernel/debug
            name: kernel-debug
      volumes:
        - name: launcherdir
          emptyDir: {}
        - name: kernel-debug
          hostPath:
            path: /sys/kernel/debug  
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-07-17T08:21:05Z"
    lastUpdateTime: "2024-07-17T08:21:05Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-07-17T08:20:37Z"
    lastUpdateTime: "2024-07-22T09:37:59Z"
    message: ReplicaSet "authorization-service-77c59f454f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 9
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
  
