apiVersion: v1
data:
  KAFKA_BROKERS: kafka-opentp-controller-0.kafka-opentp-controller-headless.kafka.svc.cluster.local:9092,kafka-opentp-controller-1.kafka-opentp-controller-headless.kafka.svc.cluster.local:9092,kafka-opentp-controller-2.kafka-opentp-controller-headless.kafka.svc.cluster.local:9092 
  KAFKA_ORDERS_TOPIC: orders
  DB_CONN_STRING: host=opentp-postgresql.postgresql dbname=opentp sslmode=disable user=opentp password=password
  DB_DRIVER_NAME: postgres
kind: ConfigMap
metadata:
  name: opentp

