apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order-monitor
  name: order-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-monitor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: order-monitor
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: opentp
        image: {{ .Values.dockerRepo }}/otp-order-monitor:{{ .Values.dockerTag }}
        imagePullPolicy: Always
        name: order-monitor
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: otpservice
      serviceAccountName: otpservice

