apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order-data-service
  name: order-data-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-data-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: order-data-service
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: opentp
        image: {{ .Values.dockerRepo }}/otp-order-data-service:{{ .Values.dockerTag }}
        imagePullPolicy: Always
        name: order-data-service
