apiVersion: v1
kind: Service
metadata:
  labels:
    app: opentp-client
  name: opentp-client
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: opentp-client
  sessionAffinity: None
  type: ClusterIP

