apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-monitor
  name: order-monitor
spec:
  ports:
  - port: 50551
    protocol: TCP
    targetPort: 50551
  selector:
    app: order-monitor
  sessionAffinity: None
  type: ClusterIP

