apiVersion: v1
kind: Service
metadata:
  name: iexg-market-data-gateway
  labels:
    app: iexg-market-data-gateway
spec:
  ports:
  - port: 50551
    name: api
  clusterIP: None
  selector:
    app: iexg-market-data-gateway
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: iexg-market-data-gateway
  name: iexg-market-data-gateway
spec:
  serviceName: "iexg-market-data-gateway"
  replicas: 2
  selector:
    matchLabels:
      app: iexg-market-data-gateway
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: iexg-market-data-gateway
        servicetype: market-data-gateway
        mic: IEXG
    spec:
      containers:
      - env:
        - name: FIX_SIM_ADDRESS
          value: iexgsimulator:50051
        - name: GATEWAY_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: {{ .Values.dockerRepo }}/otp-market-data-gateway-fixsim:{{ .Values.dockerTag }}
        imagePullPolicy: Always
        name: iexg-market-data-gateway
        ports:
        - containerPort: 50551 
          name: api 
      serviceAccount: otpservice
      serviceAccountName: otpservice
