apiVersion: v1
kind: Service
metadata:
  name: xnas-order-gateway
  labels:
    app: xnas-order-gateway
spec:
  ports:
  - port: 50551
    name: api
  clusterIP: None
  selector:
    app: xnas-order-gateway
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: xnas-order-gateway
  name: xnas-order-gateway
spec:
  serviceName: "xnas-order-gateway"
  replicas: 2
  selector:
    matchLabels:
      app: xnas-order-gateway
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: xnas-order-gateway
        servicetype: execution-venue 
        mic: XNAS
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: opentp
        env:
        - name: FIX_SOCKET_CONNECT_HOST
          value: xnassimulator
        - name: FIX_SOCKET_CONNECT_PORT
          value: "9876"
        - name: FIX_LOG_FILE_PATH
          value: /open-trading-platform/xnas-order-gateway
        - name: FIX_FILE_STORE_PATH
          value: /open-trading-platform/xnas-order-gateway
        - name: MIC
          value: XNAS
        - name: ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: {{ .Values.dockerRepo }}/otp-fix-sim-execution-venue:{{ .Values.dockerTag }}        
        imagePullPolicy: Always
        name: xnas-order-gateway
        ports:
        - containerPort: 50551 
          name: api 
        volumeMounts:
        - mountPath: /open-trading-platform
          name: execution-venue-storage
      volumes:
      - emptyDir: {}
        name: execution-venue-storage
      serviceAccount: otpservice
      serviceAccountName: otpservice
