apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: opentp-client
  name: opentp-client
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: opentp-client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: default/splunk-otel-collector
      labels:
        app: opentp-client
    spec:
      containers:
      - image: quay.io/phagen/opentp-client:1.1.0
      #- image: {{ .Values.dockerRepo }}/otp-opentp-client:{{ .Values.dockerTag }}
        imagePullPolicy: Always
        name: opentp-client
