apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: opentp-client
  name: opentp-client
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: opentp-client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: opentp-client
    spec:
      containers:
      #- image: {{ .Values.dockerRepo }}/otp-opentp-client:{{ .Values.dockerTag }}
      - image: rcastley895/opentp-client:latest
        imagePullPolicy: Always
        name: opentp-client
