apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: static-data-service
  name: static-data-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-data-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: static-data-service
    spec:
      shareProcessNamespace: true
      containers:
      - envFrom:
        - configMapRef:
            name: opentp
        # image: {{ .Values.dockerRepo }}/otp-static-data-service:{{ .Values.dockerTag }}
        image: quay.io/phagen/static-data-service:1.1.0
        imagePullPolicy: Always
        name: static-data-service
      - name: splunk-go-instrumentation
        image: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:v0.14.0-alpha
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_IP
          valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        - name: OTEL_GO_AUTO_TARGET_EXE
          value: "/app/service"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://$(NODE_IP):4317"
        - name: OTEL_SERVICE_NAME
          value: "static-data-service"
        - name: OTEL_PROPAGATORS
          value: "tracecontext,baggage"
        - name: OTEL_GO_AUTO_GLOBAL
          value: "true"
        - name: OTEL_LOG_LEVEL
          value: "debug"
        securityContext:
          runAsUser: 0
          privileged: true
