apiVersion: v1
kind: Service
metadata:
  name: envoy
  labels:
    app: envoy
    name: envoy
spec:
  type: ClusterIP
  ports:
    - port: 8082
      name: tcp-service
      targetPort: 8082
  selector:
    app: envoy