apiVersion: v1
kind: Service
metadata:
  name: xosr-market-data-gateway
  labels:
    app: xosr-market-data-gateway
spec:
  ports:
  - port: 50551
    name: api
  clusterIP: None
  selector:
    app: xosr-market-data-gateway
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: xosr-market-data-gateway
  name: xosr-market-data-gateway
spec:
  serviceName: "xosr-market-data-gateway"
  replicas: 2
  selector:
    matchLabels:
      app: xosr-market-data-gateway
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: xosr-market-data-gateway
        servicetype: market-data-gateway
        mic: XOSR
    spec:
      shareProcessNamespace: true     
      serviceAccount: otpservice
      serviceAccountName: otpservice    
      containers:
      - env:
        - name: GATEWAY_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        #image: {{ .Values.dockerRepo }}/otp-quote-aggregator:{{ .Values.dockerTag }}
        image: quay.io/phagen/quote-aggregator:1.1.0    
        imagePullPolicy: Always
        name: xosr-market-data-gateway
        ports:
        - containerPort: 50551 
          name: api 
      - name: splunk-go-instrumentation
        image: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:v0.14.0-alpha
        imagePullPolicy: IfNotPresent
        env:
          - name: NODE_IP
            valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          - name: OTEL_GO_AUTO_TARGET_EXE
            value: "/app/service"
          - name: OTEL_TRACES_EXPORTER
            value: "otlp"
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: "grpc"
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://$(NODE_IP):4317"
          - name: OTEL_SERVICE_NAME
            value: "xosr-market-data-gateway"
          - name: OTEL_PROPAGATORS
            value: "tracecontext,baggage"
          - name: OTEL_GO_AUTO_GLOBAL
            value: "true"
          - name: OTEL_LOG_LEVEL
            value: "Debug"
        securityContext:
          runAsUser: 0
          privileged: true                    

