apiVersion: v1
kind: Service
metadata:
  name: xnas-market-data-gateway
  labels:
    app: xnas-market-data-gateway
spec:
  ports:
  - port: 50551
    name: api
  clusterIP: None
  selector:
    app: xnas-market-data-gateway
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: xnas-market-data-gateway
  name: xnas-market-data-gateway
spec:
  serviceName: "xnas-market-data-gateway"
  replicas: 2
  selector:
    matchLabels:
      app: xnas-market-data-gateway
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: xnas-market-data-gateway
        servicetype: market-data-gateway
        mic: XNAS
    spec:
      shareProcessNamespace: true
      serviceAccount: otpservice
      serviceAccountName: otpservice
      containers:
      - env:
        - name: FIX_SIM_ADDRESS
          value: xnassimulator:50051
        - name: GATEWAY_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        #image: {{ .Values.dockerRepo }}/otp-market-data-gateway-fixsim:{{ .Values.dockerTag }}
        image: quay.io/phagen/market-data-gateway-fixsim:1.1.0
        imagePullPolicy: Always
        name: xnas-market-data-gateway
        ports:
        - containerPort: 50551 
          name: api 
      - name: splunk-go-instrumentation
        image: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:v0.14.0-alpha
        imagePullPolicy: IfNotPresent
        env:
          - name: NODE_IP
            valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          - name: OTEL_GO_AUTO_TARGET_EXE
            value: "/app/service"
          - name: OTEL_TRACES_EXPORTER
            value: "otlp"
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: "grpc"
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://$(NODE_IP):4317"
          - name: OTEL_SERVICE_NAME
            value: "xnas-market-data-gateway"
          - name: OTEL_PROPAGATORS
            value: "tracecontext,baggage"
          - name: OTEL_GO_AUTO_GLOBAL
            value: "true"
          - name: OTEL_LOG_LEVEL
            value: "debug"
        securityContext:
          runAsUser: 0
          privileged: true
